### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by kuldeepjambhulkar** [plxity/achievementsof.life#45]
@plxity 

Either there is a typo in this URL or the site is down
https://www.achievementsof.life/

![image](https://user-images.githubusercontent.com/89466207/216248810-195b6a3b-bbc5-4c23-a977-5a87213f66ed.png)

**Comment by srivenkat13** [comment]
I think the domain has expired

**Comment by plxity** [comment]
Yes, the domain has expired. Meanwhile, you can use this link -- https://achievementsof-life.vercel.app/  @kuldeepjambhulkar @srivenkat13
